<?php
// auto-generated by Kohana-Zend Autocomplete
// Developed by Peter Bowyer, Maple Design (http://www.mapledesign.co.uk/code/
// Last generated: 2010-01-02 20:24:00 MSK

// File Z:/home/champ/www/system/controllers/captcha.php:
Class Captcha extends Captcha_Controller {}

// File Z:/home/champ/www/system/controllers/template.php:
Class Your extends Your_Controller { function __construct(); }

// File Z:/home/champ/www/system/helpers/arr.php:
Class arr extends arr_Core {}

// File Z:/home/champ/www/system/helpers/cookie.php:
Class cookie extends cookie_Core {}

// File Z:/home/champ/www/system/helpers/date.php:
Class date extends date_Core {}

// File Z:/home/champ/www/system/helpers/download.php:
Class download extends download_Core {}

// File Z:/home/champ/www/system/helpers/email.php:
Class email extends email_Core {}

// File Z:/home/champ/www/system/helpers/expires.php:
Class expires extends expires_Core {}

// File Z:/home/champ/www/system/helpers/feed.php:
Class feed extends feed_Core {}

// File Z:/home/champ/www/system/helpers/file.php:
Class file extends file_Core {}

// File Z:/home/champ/www/system/helpers/form.php:
Class form extends form_Core {}

// File Z:/home/champ/www/system/helpers/format.php:
Class format extends format_Core {}

// File Z:/home/champ/www/system/helpers/html.php:
Class html extends html_Core {}

// File Z:/home/champ/www/system/helpers/inflector.php:
Class inflector extends inflector_Core {}

// File Z:/home/champ/www/system/helpers/num.php:
Class num extends num_Core {}

// File Z:/home/champ/www/system/helpers/remote.php:
Class remote extends remote_Core {}

// File Z:/home/champ/www/system/helpers/request.php:
Class request extends request_Core {}

// File Z:/home/champ/www/system/helpers/security.php:
Class security extends security_Core {}

// File Z:/home/champ/www/system/helpers/text.php:
Class text extends text_Core {}

// File Z:/home/champ/www/system/helpers/upload.php:
Class upload extends upload_Core {}

// File Z:/home/champ/www/system/helpers/url.php:
Class url extends url_Core {}

// File Z:/home/champ/www/system/helpers/valid.php:
Class valid extends valid_Core {}

// File Z:/home/champ/www/system/libraries/Calendar.php:
Class Calendar extends Calendar_Core { function __construct($month = NULL, $year = NULL); }

// File Z:/home/champ/www/system/libraries/Calendar_Event.php:
Class Calendar_Event extends Calendar_Event_Core {}

// File Z:/home/champ/www/system/libraries/Captcha.php:
Class Captcha extends Captcha_Core { function __construct($group = NULL); }

// File Z:/home/champ/www/system/libraries/Database.php:
Class Database extends Database_Core { function __construct($config = array()); }

// File Z:/home/champ/www/system/libraries/Encrypt.php:
Class Encrypt extends Encrypt_Core { function __construct($config = FALSE); }

// File Z:/home/champ/www/system/libraries/Input.php:
Class Input extends Input_Core { function __construct(); }

// File Z:/home/champ/www/system/libraries/Model.php:
Class Model extends Model_Core { function __construct(); }

// File Z:/home/champ/www/system/libraries/ORM.php:
Class ORM extends ORM_Core { function __construct($id = NULL); }

// File Z:/home/champ/www/system/libraries/ORM_Iterator.php:
Class ORM_Iterator extends ORM_Iterator_Core { function __construct(ORM $model, Database_Result $result); }

// File Z:/home/champ/www/system/libraries/ORM_Tree.php:
Class ORM_Tree extends ORM_Tree_Core {}

// File Z:/home/champ/www/system/libraries/ORM_Versioned.php:
Class ORM_Versioned extends ORM_Versioned_Core {}

// File Z:/home/champ/www/system/libraries/Pagination.php:
Class Pagination extends Pagination_Core { function __construct($config = array()); }

// File Z:/home/champ/www/system/libraries/Profiler.php:
Class Profiler extends Profiler_Core { function __construct(); }

// File Z:/home/champ/www/system/libraries/Profiler_Table.php:
Class Profiler_Table extends Profiler_Table_Core {}

// File Z:/home/champ/www/system/libraries/Router.php:
Class Router extends Router_Core {}

// File Z:/home/champ/www/system/libraries/Session.php:
Class Session extends Session_Core { function __construct(); }

// File Z:/home/champ/www/system/libraries/Tagcloud.php:
Class Tagcloud extends Tagcloud_Core { function __construct(array $elements, $min_size = NULL, $max_size = NULL, $shuffle = FALSE); }

// File Z:/home/champ/www/system/libraries/URI.php:
Class URI extends URI_Core {}

// File Z:/home/champ/www/system/libraries/Validation.php:
Class Validation extends Validation_Core { function __construct(array $array); }

// File Z:/home/champ/www/system/libraries/View.php:
Class View extends View_Core { function __construct($name = NULL, $data = NULL, $type = NULL); }

// File Z:/home/champ/www/modules/auth/libraries/Auth.php:
Class Auth extends Auth_Core { function __construct($config = array()); }

// File Z:/home/champ/www/application/controllers/ac.php:
Class Ac extends Ac_Controller {}

// File Z:/home/champ/www/application/controllers/admin/main.php:
Class Main extends Main_Controller {}

// File Z:/home/champ/www/application/controllers/admin/team.php:
Class Team extends Team_Controller {}

// File Z:/home/champ/www/application/controllers/admin.php:
Class Admin extends Admin_Controller { function __construct(); }

// File Z:/home/champ/www/application/controllers/match.php:
Class Match extends Match_Controller { function __construct(); }

// File Z:/home/champ/www/application/controllers/user.php:
Class User extends User_Controller {}

// File Z:/home/champ/www/application/libraries/Widget.php:
Class Widget extends Widget_Core {}

